### ISSUE TITLE
Question about convert scene flow to 3D motion vector

### ISSUE THREAD

**Issue by HaiyiMei** [ravikt/sceneednet#1]
Hey, great job! I've read the paper and got a question about how to convert scene flow from a 4D vector in the image space as (u; v; d0; d1) [[1]](https://arxiv.org/abs/1801.04720) to a 3D motion vector described in the paper?
I've found the processing code [readfiles.py](https://github.com/ravikt/sceneednet/blob/master/readfiles.py) which simply minus the depth map as [dZ](https://github.com/ravikt/sceneednet/blob/3c9274e2e7e7f30c2a4699418704c72d490b7ed0/readfiles.py#L102). And have no idea why `dX` and `dY` are obtained by this formula(line 73 ~ line 104 in readfiles.py). Could you please explain it to me? Thanks a lot!

> Reference
> [1] R. Schuster, C. Bailer, O. Wasenm¨uller, and D. Stricker, “Combining stereo disparity and optical flow for basic scene flow,” in Commercial Vehicle Technology 2018. Springer, 2018, pp. 90–101.

**Comment by ravikt** [comment]
The optical flow and disparity are given in pfm format. These contains values for each pixel. We can think of scene flow as 4D vector in image space as (u,v, d0, d1)^T. This 4D vector can be converted from image representation to world representation. This is what we have used as ground truth in our work. Scene flow in 3D (dx, dy, dz)^T can be computed if 3D positions for pixels at two consecutive steps are known. The two 3D points can be computed with standard stereo disparity formula and pinhole projection.

z0 = focal_length * baseline / d0
x0 = (x - x_offset) * z0 / focal_length
y0 = (y - y_offset) * z0 / focal_length

z1 = focal_length * baseline / d1
x1 = (x + u - x_offset) * z1 / focal_length
y1 = (y + v - y_offset) * z1 / focal_length

focal length and baseline are provided in the FlyingThings3D dataset. d0 and d1 and disparity values. The x- and y-offsets are the offsets of your principal points. This can be obtained from camera pinhole model.

The difference of both points is the scene flow vector dx = x1 - x0, dy
= y1 - y0, dz = z1 - z0
(x,y are the pixel positions, _0 and _1 are the 3D point components at
time t0 and t1 respectively)
